"""per_provider_llm_config

Revision ID: 2e1ac9ee6175
Revises: 983d0a28b216
Create Date: 2026-04-25 01:33:34.762582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1ac9ee6175'
down_revision: Union[str, None] = '983d0a28b216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_llm_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.drop_constraint('uq_user_llm_configs_user_id', type_='unique')
        batch_op.create_unique_constraint('uq_user_llm_configs_user_provider', ['user_id', 'provider'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_llm_configs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_llm_configs_user_provider', type_='unique')
        batch_op.create_unique_constraint('uq_user_llm_configs_user_id', ['user_id'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
