"""add_user_llm_configs

Revision ID: 983d0a28b216
Revises: ccfd853274c4
Create Date: 2026-04-24 22:36:48.169307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983d0a28b216'
down_revision: Union[str, None] = 'ccfd853274c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_llm_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_llm_configs_user_id')
    )
    op.create_index(op.f('ix_user_llm_configs_user_id'), 'user_llm_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_llm_configs_user_id'), table_name='user_llm_configs')
    op.drop_table('user_llm_configs')
    # ### end Alembic commands ###
