"""add_custom_models

Revision ID: afcc90689f85
Revises: 2e1ac9ee6175
Create Date: 2026-04-25 01:52:27.163518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcc90689f85'
down_revision: Union[str, None] = '2e1ac9ee6175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_llm_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_models', sa.Text(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_llm_configs', schema=None) as batch_op:
        batch_op.drop_column('custom_models')

    # ### end Alembic commands ###
